const express=require('express')
const dotenv=require('dotenv').config()
const app=express()
const dbConnection=require('./DB/dbConnection')
const userRoute=require('./Routes/user.Route')
const supplierRoute=require('./Routes/supplier.Route')
const medicineRouter=require('./Routes/medicine.Route')
const inventoryRoute=require('./Routes/inventory.Route')
const batchRoute=require('./Routes/batch.Route')
const orderHistoryRoute=require('./Routes/orderHistory.Route')
const salesTransactionRoute=require('./Routes/salesTransaction.Route')
const paymentMethodRoute=require('./Routes/paymentMethod.Route')
const receiptRoute=require('./Routes/receipt.Route')
const taxRoute=require('./Routes/tax.Route')
const discountRoute=require('./Routes/discount.Route')
const refundRoute=require('./Routes/refund.Route')
const customerRoute=require('./Routes/customer.Route')
const medicalHistoryRoute=require('./Routes/medicalHistory.Route')
const doctorRoute=require('./Routes/doctor.Route')
const prescriptionRoute=require('./Routes/prescription.Route')
dbConnection()
app.use(express.json())
app.use(express.urlencoded({extended:true}))

app.use('/api/user',userRoute)
app.use('/api/supplier',supplierRoute)
app.use('/api/medicine',medicineRouter)
app.use('/api/inventory',inventoryRoute)
app.use('/api/batch',batchRoute)
app.use('/api/orderhistory',orderHistoryRoute)
app.use('/api/salestransaction',salesTransactionRoute)
app.use('/api/paymentmethod',paymentMethodRoute)
app.use('/api/receipt',receiptRoute)
app.use('/api/tax',taxRoute)
app.use('/api/discount',discountRoute)
app.use('/api/refund',refundRoute)
app.use('/api/customer',customerRoute)
app.use('/api/medicalhistory',medicalHistoryRoute)
app.use('/api/doctor',doctorRoute)
app.use('/api/prescription',prescriptionRoute)
const port=process.env.PORT || 6000


app.listen(port,()=>{
    console.log(`server is running on port ${port}`)
})